title: APIs.json Builder
description: This is a builder for the APIs.json / APIs.yaml API discovery format.
url: http://apisjson.org
image: https://s3.amazonaws.com/kinlane-productions2/api-evangelist-logos/api-evangelist-red-seal.png
logo: https://kinlane-productions2.s3.amazonaws.com/apis-json/apis-json-logo.jpg

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 25
paginate_path: "/blog/page:num"

github_user: api-evangelist
github_repo: design
github_branch: gh-pages
